### ISSUE TITLE
WxMaProperties 读取配置为null

### ISSUE THREAD

**Issue by dujiliang** [binarywang/weixin-java-miniapp-demo#10]
![image](https://user-images.githubusercontent.com/33058428/49062384-ea797780-f24e-11e8-9605-f0a596e22620.png)

this.properties.getConfigs()是null

**Comment by binarywang** [comment]
你的配置文件有吗？

**Comment by dujiliang** [comment]
配置文件如下：

WxMaProperties中：


------------------ 原始邮件 ------------------
发件人: "Binary Wang"<notifications@github.com>;
发送时间: 2018年11月27日(星期二) 下午2:49
收件人: "binarywang/weixin-java-miniapp-demo"<weixin-java-miniapp-demo@noreply.github.com>;
抄送: "SelfImp"<274502936@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [binarywang/weixin-java-miniapp-demo] WxMaProperties 读取配置为null (#10)




你的配置文件有吗？

**Comment by binarywang** [comment]
你这是类文件

**Comment by dujiliang** [comment]
配置文件如上图


------------------ 原始邮件 ------------------
发件人: "Binary Wang"<notifications@github.com>;
发送时间: 2018年11月27日(星期二) 下午3:29
收件人: "binarywang/weixin-java-miniapp-demo"<weixin-java-miniapp-demo@noreply.github.com>;
抄送: "SelfImp"<274502936@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [binarywang/weixin-java-miniapp-demo] WxMaProperties 读取配置为null (#10)




你这是类文件

**Comment by yhwpeng** [comment]
遇到同样的问题，WxMaProperties读取的配置为null

**Comment by yhwpeng** [comment]
问题已解决，demo中的yml配置有误，configs后面缺 [0]
wx:
  miniapp:
    configs[0]:
      appid:

**Comment by yhwpeng** [comment]
仔细看了下demo ，configs 前面有个  “-” 符号，楼主应该也是丢了

**Comment by binarywang** [comment]
估计是以为横线是注释就给丢了？

**Comment by binarywang** [comment]
认真按照demo说明配置就没问题

**Comment by lixunhui** [comment]
> [0]

按照你说的改掉之后也不行呀

**Comment by goodls-cs** [comment]
配置文件改名为：application.yml
