### ISSUE TITLE
你自己的demo为什么还报这个错？

### ISSUE THREAD

**Issue by baishuirouqing** [binarywang/weixin-java-miniapp-demo#12]
java.lang.ClassNotFoundException: org.apache.http.client.HttpRequestRetryHandler

**Comment by binarywang** [comment]
没听别人提过这种错误，仔细检查下你改了什么？或者什么相关东西没下载下来？

**Comment by binarywang** [comment]
没消息了？

**Comment by a442914168** [comment]
他yml配置错了
wx:
  miniapp:
    configs:

就可以了
