### ISSUE TITLE
服务端接收小程序会话的参数 会引发错误

### ISSUE THREAD

**Issue by chaohony** [binarywang/weixin-java-miniapp-demo#16]
![image](https://user-images.githubusercontent.com/29838799/56090204-9efbf900-5ed1-11e9-8134-00182d468484.png)

用demo中的这个方法去接收总是会报错,自己去打印了request中所有的参数, 发现在明文条件下,request请求参数中是不带msg_signature和encrypt_type, 目前这样取值直接就报错了

![image](https://user-images.githubusercontent.com/29838799/56090210-b804aa00-5ed1-11e9-8579-0fc4cfadf0fe.png)
多加一个默认值就好了

**Comment by binarywang** [comment]
正确姿势应该是加`, required = false`
