### ISSUE TITLE
SpringBoot获取YML配置为空，拿不到配置文件

### ISSUE THREAD

**Issue by lixunhui** [binarywang/weixin-java-miniapp-demo#18]
cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'wxMaConfiguration': Invocation of init method failed; nested exception is java.lang.RuntimeException: 大哥，拜托先看下项目首页的说明（readme文件），添加下相关配置，注意别配错了！

`wx:
  miniapp:
    configs:
      - appid: wxf65b8972546sdfsa5
        secret: c9ff803754ada88c20323432dsdfsdfds
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON`

其他配置和Demo一样，求解答

**Comment by eyutongling** [comment]
配置多个appid 时，好像只读取到一个，demo是这样子的吗

**Comment by binarywang** [comment]
别好像是啊，自己看源码不能确认吗？

**Comment by binarywang** [comment]
楼主的问题自己在仔细看下
