### ISSUE TITLE
解密手机号get会失败, 请改为post

### ISSUE THREAD

**Issue by PlexPt** [binarywang/weixin-java-miniapp-demo#19]
https://github.com/binarywang/weixin-java-miniapp-demo/blob/f73a8427d9f4ba33af5203ce82bec20cda219e10/src/main/java/com/github/binarywang/demo/wx/miniapp/controller/WxMaUserController.java#L79

**Comment by binarywang** [comment]
自己改就是了，用什么方式不重要，重要是你知道怎么调用sdk里的接口方法
