### ISSUE TITLE
项目依赖的weixin-java-miniapp开源吗?

### ISSUE THREAD

**Issue by joyfun** [binarywang/weixin-java-miniapp-demo#22]
找了下 
<groupId>com.github.binarywang</groupId>
     <artifactId>weixin-java-miniapp</artifactId>
这个的源码貌似没找到 请问这个项目开源吗?

**Comment by binarywang** [comment]
必须开源啊，发布到maven中央仓库的都是开源的，看我的首页有链接。

**Comment by fushenglaodie** [comment]
weixin-java-miniapp支持多个小程序，
那如果这些小程序都需要提供微信支付的接口怎么办。
weixin-java-pay好像不支持多个小程序呀。

**Comment by binarywang** [comment]
> weixin-java-miniapp支持多个小程序，
> 那如果这些小程序都需要提供微信支付的接口怎么办。
> weixin-java-pay好像不支持多个小程序呀。

每个小程序对应一个微信支付账号，因此针对每个小程序你创建一个config和对应的service即可
