### ISSUE TITLE
调用接口的时候每次要传appid，是不是不安全，并且不够通用

### ISSUE THREAD

**Issue by Secret-zero** [binarywang/weixin-java-miniapp-demo#25]
@RestController
@RequestMapping("/wx/media/{appid}")
public class WxMaMediaController 
我看到demo中调用的方法都要传appid,写法和公众号的写法不太一样，不知道是不是要更改

**Comment by binarywang** [comment]
appid只是个标识，如果你觉得不放心，可以自行定义为其他任何字符，只要你能区分不同小程序即可。

**Comment by binarywang** [comment]
这个demo是通用的，支持多个小程序接入，如果你只是一个小程序，完全可以去掉对应的参数
