### ISSUE TITLE
获取用户信息时候报错

### ISSUE THREAD

**Issue by 1157009511** [binarywang/weixin-java-miniapp-demo#28]
Resolved exception caused by Handler execution: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

**Comment by 1157009511** [comment]
> Resolved exception caused by Handler execution: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

抱歉，是个人问题导致

**Comment by zhangyangx** [comment]
我也碰到了，请问是什么原因。。

**Comment by binarywang** [comment]
请参考WxJava的wiki里的常见问题
