### ISSUE TITLE
获取直播间列表的商品信息的商品图片地址coverImgUrl值为空

### ISSUE THREAD

**Issue by Alixhan** [binarywang/weixin-java-miniapp-demo#31]
上个版本是可以获取到coverImg的 这个版本的字段换成了converImgUrl，导致无法获取图片地址，
查看了微信api返回的数据 依然是cover_img

**Comment by binarywang** [comment]
具体接口问题可以到WxJava里讨论，谢谢

**Comment by binarywang** [comment]
新版本即将修复
