### ISSUE TITLE
获取用户或用户手机号json转换问题

### ISSUE THREAD

**Issue by zhangyangx** [binarywang/weixin-java-miniapp-demo#33]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

**Comment by zhangyangx** [comment]
包版本3.8.0

**Comment by lizhigang-953130828** [comment]
没有解决吧，包版本换了问题还是在

**Comment by chenweibo** [comment]
@zhangyangx  你解决了 一样问题

**Comment by UFO233** [comment]
> @zhangyangx 你解决了 一样问题

你们都解决了吗，我也是一样的问题
