### ISSUE TITLE
该项目有没有实现ocr功能

### ISSUE THREAD

**Issue by Secret-zero** [binarywang/weixin-java-miniapp-demo#34]
官方接口的地址是这个：https://api.weixin.qq.com/cv/ocr/comm?img_url=ENCODE_URL&access_token=ACCESS_TOCKEN，没有在
weixin-java-miniapp项目中找到OCR模块，不知道要如何实现这个功能

**Comment by binarywang** [comment]
有啊，你确定仔细看了？

**Comment by Secret-zero** [comment]
我只看到了mp里面有，miniAPP这个项目里面暂时没看到




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Binary Wang"<notifications@github.com&gt;; 
发送时间: 2020年8月27日(星期四) 下午2:32
收件人: "binarywang/weixin-java-miniapp-demo"<weixin-java-miniapp-demo@noreply.github.com&gt;; 
抄送: "719769132"<719769132@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [binarywang/weixin-java-miniapp-demo] 该项目有没有实现ocr功能 (#34)





 
有啊，你确定仔细看了？

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/blob/master/weixin-java-miniapp/src/main/java/cn/binarywang/wx/miniapp/api/impl/WxMaOcrServiceImpl.java

请参考此类

**Comment by Secret-zero** [comment]
抱歉，我之前下的wxjava没这个，没看最新的版本，非常感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Binary Wang"<notifications@github.com&gt;; 
发送时间: 2020年8月27日(星期四) 下午2:36
收件人: "binarywang/weixin-java-miniapp-demo"<weixin-java-miniapp-demo@noreply.github.com&gt;; 
抄送: "719769132"<719769132@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [binarywang/weixin-java-miniapp-demo] 该项目有没有实现ocr功能 (#34)





 
Closed #34.

**Comment by binarywang** [comment]
> 抱歉，我之前下的wxjava没这个，没看最新的版本，非常感谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Binary Wang"<notifications@github.com&gt;; 发送时间: 2020年8月27日(星期四) 下午2:36 收件人: "binarywang/weixin-java-miniapp-demo"<weixin-java-miniapp-demo@noreply.github.com&gt;; 抄送: "719769132"<719769132@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [binarywang/weixin-java-miniapp-demo] 该项目有没有实现ocr功能 (#34) Closed #34. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

注意看版本更新日志就好了，这个是上个版本刚刚加入的
