### ISSUE TITLE
微信公众号和小程序的包可以共用吗

### ISSUE THREAD

**Issue by wcxdandan** [binarywang/weixin-java-miniapp-demo#36]
微信公众号和小程序的包可以共用吗

weixin-java-cp /mp   和weixin-java-miniapp   能共用吗？

**Comment by binarywang** [comment]
当然可以

**Comment by wcxdandan** [comment]
> 
![image](https://user-images.githubusercontent.com/59184784/92686615-96308080-f36c-11ea-901b-b2aa2e7f5447.png)

**Comment by wcxdandan** [comment]
![image](https://user-images.githubusercontent.com/59184784/92686688-b9f3c680-f36c-11ea-8e8a-4b751a35a57c.png)

**Comment by wcxdandan** [comment]
其他几个型号是 2.5.0    weixin-java-miniapp 是3.9.0

**Comment by wcxdandan** [comment]
![image](https://user-images.githubusercontent.com/59184784/92686997-4d2cfc00-f36d-11ea-8ad1-00e5da833fe8.png)

**Comment by binarywang** [comment]
不要使用不同的版本，有冲突

**Comment by binarywang** [comment]
共用的common包

**Comment by wcxdandan** [comment]
好的 谢谢啦 换个高版本的型号就好了

**Comment by wcxdandan** [comment]
你好 有对应的版本号适配图吗？

**Comment by wcxdandan** [comment]
公众号和小程序 对应的型号适配？

**Comment by binarywang** [comment]
> 你好 有对应的版本号适配图吗？

没有，不过可以确定的是，使用同一个版本肯定没问题

**Comment by wcxdandan** [comment]
一般哪个比较稳定一些？

**Comment by binarywang** [comment]
> 一般哪个比较稳定一些？

你不换版本，一直用，而且没有需求变更，或者微信没有对接口进行调整，那就很稳定。

**Comment by wcxdandan** [comment]
您好 我这边微信公众号是2.5.0的版本号    支付是3.4.0的版本号！用的一直稳定   需要对应哪个版本号的miniapp？ 我这边一升级高版本的微信公众号版本号  支付就一堆错         mini最低的版本号就是 2.6.x  没法和微信公众号的版本对应

**Comment by wcxdandan** [comment]
大神 请教一下

**Comment by binarywang** [comment]
针对你的问题，如果不想影响现有功能，建议小程序模块使用独立微服务，避免产生版本冲突问题
