### ISSUE TITLE
启动编译报错

### ISSUE THREAD

**Issue by wenhua-huang** [binarywang/weixin-java-miniapp-demo#37]
springboot configuration annotaion processor not configured

引进jar   <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>  
可以解决

**Comment by binarywang** [comment]
这个本来不就有吗？

**Comment by wenhua-huang** [comment]
不好意思，我加重复了，是我本地一直报那个错。后面自己好了。
