### ISSUE TITLE
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'wxMaConfiguration': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: me/chanjar/weixin/common/api/WxOcrService

### ISSUE THREAD

**Issue by Wuou** [binarywang/weixin-java-miniapp-demo#38]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'wxMaConfiguration': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: me/chanjar/weixin/common/api/WxOcrService

**Comment by binarywang** [comment]
版本问题，检查对应包的版本是否一致

**Comment by zhusaidong** [comment]
检查对应包的版本是否一致是什么意思？
我就依赖了一个包啊，对应包是哪个包？

**Comment by binarywang** [comment]
weixin-java-common包

**Comment by zhusaidong** [comment]
知道了，我依赖的`wx-java-mp-spring-boot-starter`和`wx-java-miniapp-spring-boot-starter`版本不一致导致的。感谢。
