### ISSUE TITLE
在同时获取SessionKey 后直接获取用户手机号会异常

### ISSUE THREAD

**Issue by chenweibo** [binarywang/weixin-java-miniapp-demo#40]
WxMaJscode2SessionResult session = wxService.getUserService().getSessionInfo(code);
  WxMaPhoneNumberInfo phoneNoInfo = wxService.getUserService().getPhoneNoInfo(session.getSessionKey(), encryptedData, iv);
单独获取就不会。
可能是因为session接口还没完成就已经运行了 下面获取手机号。
现在的 微信小程序登陆基本上 获取手机号用作用户登陆。这样子合并操作 会导致
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
这个异常。
单独使用却不会出。
然后 这个异常的出现后 第二次请求的时候就不会出现。 可能是 第一次请求腾讯接口有相应延迟。 第二次就速度快了。就不会出异常

**Comment by chenweibo** [comment]
没有序列号完完全全拿 demo里面的文件跑
<img width="1134" alt="Snipaste_2021-01-15_16-06-29" src="https://user-images.githubusercontent.com/19586007/104698076-bec9ec00-574b-11eb-80be-cd3af200b959.png">

**Comment by chenweibo** [comment]
<img width="1134" alt="Snipaste_2021-01-15_16-06-29" src="https://user-images.githubusercontent.com/19586007/104698116-ce493500-574b-11eb-8dd4-185831dd3773.png">

**Comment by binarywang** [comment]
请查阅wxjava的wiki常见问题

**Comment by binarywang** [comment]
或者参考wxjava的issue置顶区问题

**Comment by chenweibo** [comment]
thinks
