### ISSUE TITLE
微信小程序授权登录时，json转WxMaPhoneNumberInfo时，json乱码

### ISSUE THREAD

**Issue by DavidHuang1996** [binarywang/weixin-java-miniapp-demo#44]
![image](https://user-images.githubusercontent.com/57939804/119079652-198d9000-ba2b-11eb-8949-5cb30a391cf1.png)
![image](https://user-images.githubusercontent.com/57939804/119079667-20b49e00-ba2b-11eb-9189-8c52b75d4175.png)
![image](https://user-images.githubusercontent.com/57939804/119080166-26f74a00-ba2c-11eb-949a-a20d8d02129c.png)

出现乱码的几率很小

**Comment by binarywang** [comment]
看WxJava 的wiki页面里的常见问题

**Comment by DavidHuang1996** [comment]
谢谢，是前端那个session_key过期了。
