### ISSUE TITLE
使用wxService.getUserService().getUserInfo()无法获取用户信息

### ISSUE THREAD

**Issue by yt326078** [binarywang/weixin-java-miniapp-demo#45]
![image](https://user-images.githubusercontent.com/45777322/119758653-74b2fd00-bed9-11eb-9312-7e5e61c8e8b3.png)
如图所示:
调用方法返回的对象中,nickName为微信用户,language、city、province、country都为空。

**Comment by binarywang** [comment]
这个是官方做的调整，注意看官方公告
