### ISSUE TITLE
WxMaProperties获取不到配置信息

### ISSUE THREAD

**Issue by bantu4me** [binarywang/weixin-java-miniapp-demo#46]
版本4.1.0 
配置文件名修改为application.yml
配置文件内容
`
logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.miniapp: debug
    cn.binarywang.wx.miniapp: debug
wx:
  miniapp:
    configs:
      appid: wx428b06bf3806d997 #微信小程序的appid
      secret: 24d0c825a5e62eede5ae660c68b75670 #微信小程序的Secret
      token: #微信小程序消息服务器配置的token
      aesKey: #微信小程序消息服务器配置的EncodingAESKey
      msgDataFormat: JSON

`

运行报错
大哥，拜托先看下项目首页的说明（readme文件），添加下相关配置，注意别配错了！

**Comment by jason233** [comment]
不行哦

**Comment by binarywang** [comment]
看配置就知道你少了-导致的，故意删除的？
