### ISSUE TITLE
支付相关的参数怎么没有支持？

### ISSUE THREAD

**Issue by a132** [binarywang/weixin-java-miniapp-demo#9]
WxMaInMemoryConfig 这个类里面，不考虑加入一些支付的参数吗？

**Comment by binarywang** [comment]
支付有单独的模块

**Comment by a132** [comment]
感谢楼主的解答。
我仿照楼主的支持多个小程序后台写了相关的支付代码（也是用了你提供的库），但是发现有个问题很难解决，就是接收退款通知的时候要根据商户的 mchKey 去解密信息，但是多个小程序的回调地址是一样的，这个时候是无法知道哪个商户的mchKey的。
我能想到的办法就是把回调地址配成不一样，而在回调接口里将取配置的地方写死。
不知道楼主有什么更好的建议吗？
